GO
USE KBAFFA
GO

	CREATE PROCEDURE MODIFICAR_ESTADO
	@CODIGO_ESTADO INT,
	@NOMBRE_ESTADO VARCHAR(30)
	AS
	UPDATE ESTADO
	SET ESTADO.NOMBRE_ESTADO = @NOMBRE_ESTADO
	WHERE ESTADO.CODIGO_ESTADO = @CODIGO_ESTADO

	EXEC MODIFICAR_ESTADO 1,'Abierto'
	
	CREATE PROCEDURE MODIFICAR_CLIENTE
	@IDENTIFICACION_CLIENTE BIGINT,
	@NOMBRE_CLIENTE VARCHAR(100),
	@CORREO_CLIENTE VARCHAR(100),
	@TELEFONO_CLIENTE BIGINT
	AS
	UPDATE CLIENTE
	SET IDENTIFICACION_CLIENTE = @IDENTIFICACION_CLIENTE, NOMBRE_CLIENTE = @NOMBRE_CLIENTE , CORREO_CLIENTE = @CORREO_CLIENTE, TELEFONO_CLIENTE = @TELEFONO_CLIENTE
	WHERE IDENTIFICACION_CLIENTE = @IDENTIFICACION_CLIENTE
	
	EXEC MODIFICAR_CLIENTE 1,'Ferney','JUAN@GMAIL.COM',123
	SELECT *FROM LLENAR_CLIENTE

	CREATE PROCEDURE MODIFICAR_PROCURADOR
	@IDENTIFICACION_PROCURADOR BIGINT,
	@NOMBRE_PROCURADOR VARCHAR (100),
	@TELEFONO_PROCURADOR BIGINT,
	@CORREO_PROCURADOR VARCHAR(100),
	@TIPO_PODER VARCHAR (100)
	AS
	UPDATE PROCURADOR
	SET NOMBRE_PROCURADOR = @NOMBRE_PROCURADOR , TELEFONO_PROCURADOR= @TELEFONO_PROCURADOR, CORREO_PROCURADOR = @CORREO_PROCURADOR,
	TIPO_PODER = @TIPO_PODER
	WHERE IDENTIFICACION_PROCURADOR = @IDENTIFICACION_PROCURADOR;

	CREATE PROCEDURE MODIFICAR_GABINETE
	@CODIGO_CREDENCIAL BIGINT,
	@NOMBRE_CASO VARCHAR(100),
	@DESCRIPCION_CASO VARCHAR (100),
	@FECHA_INICIO DATETIME ,
	@FECHA_FIN DATETIME,
	@ESTADO_CASO INT,
	@CLIENTE_CASO BIGINT,
	@PROCURADOR_CASO BIGINT
	AS
	UPDATE GABINETE
	SET NOMBRE_CASO = @NOMBRE_CASO , DESCRIPCION_CASO = @DESCRIPCION_CASO, FECHA_INICIO = @FECHA_INICIO,
	FECHA_FIN = @FECHA_FIN , ESTADO_CASO = @ESTADO_CASO, CLIENTE_CASO = @CLIENTE_CASO , PROCURADOR_CASO = @PROCURADOR_CASO
	WHERE CODIGO_CREDENCIAL = @CODIGO_CREDENCIAL

	CREATE PROCEDURE MODIFICAR_AGENDA
	@NUMERO_AGENDA BIGINT,
	@CASO BIGINT,
	@PROCURADOR_AGENDA BIGINT,
	@CLIENTE_AGENDA BIGINT
	AS
	UPDATE AGENDA
	SET CASO = @CASO , PROCURADOR_AGENDA = @PROCURADOR_AGENDA , CLIENTE_AGENDA = @CLIENTE_AGENDA
	WHERE NUMERO_AGENDA = @NUMERO_AGENDA
