GO
USE KBAFFA
GO

	CREATE PROCEDURE INSERTAR_ESTADO
	@NOMBRE_ESTADO VARCHAR (30)
	AS
	INSERT INTO ESTADO 
	VALUES (@NOMBRE_ESTADO)

	CREATE PROCEDURE INSERTAR_PROCURADOR
	@IDENTIFICACION_PROCURADOR BIGINT ,
	@NOMBRE_PROCURADOR VARCHAR (100),
	@TELEFONO_PROCURADOR BIGINT,
	@CORREO_PROCURADOR VARCHAR(100),
	@TIPO_PODER VARCHAR (100)
	AS
	INSERT INTO PROCURADOR
	VALUES (@IDENTIFICACION_PROCURADOR,@NOMBRE_PROCURADOR,@TELEFONO_PROCURADOR,@CORREO_PROCURADOR,@TIPO_PODER);

	CREATE PROCEDURE INSERTAR_CLIENTE
	@IDENTIFICACION_CLIENTE BIGINT,
	@NOMBRE_CLIENTE VARCHAR (100),
	@CORREO_CLIENTE VARCHAR (100),
	@TELEFONO_CLIENTE BIGINT
	AS 
	INSERT INTO CLIENTE
	VALUES (@IDENTIFICACION_CLIENTE,@NOMBRE_CLIENTE,@CORREO_CLIENTE,@TELEFONO_CLIENTE);

	CREATE PROCEDURE INSERTAR_GABINETE
	@NOMBRE_CARSO VARCHAR(100),
	@DESCRIPCION_CASO VARCHAR(200),
	@FECHA_INICIO DATETIME,
	@FECHA_FIN DATETIME,
	@ESTADO_CASO INT,
	@CLIENTE_CASO BIGINT,
	@PROCURADOR_CASO BIGINT
	AS
	INSERT INTO GABINETE
	VALUES (@NOMBRE_CARSO,@DESCRIPCION_CASO,@FECHA_INICIO,@FECHA_FIN,@ESTADO_CASO,@CLIENTE_CASO,@PROCURADOR_CASO);