GO
USE KBAFFA
GO

	CREATE PROCEDURE INSERTAR_ESTADO
	@NOMBRE_ESTADO VARCHAR (30)
	AS
	INSERT INTO ESTADO 
	VALUES (@NOMBRE_ESTADO)

	EXEC INSERTAR_ESTADO 'Archivado'
	
	CREATE PROCEDURE INSERTAR_PROCURADOR
	@IDENTIFICACION_PROCURADOR BIGINT ,
	@NOMBRE_PROCURADOR VARCHAR (100),
	@TELEFONO_PROCURADOR BIGINT,
	@CORREO_PROCURADOR VARCHAR(100),
	@TIPO_PODER VARCHAR (100)
	AS
	INSERT INTO PROCURADOR
	VALUES (@IDENTIFICACION_PROCURADOR,@NOMBRE_PROCURADOR,@TELEFONO_PROCURADOR,@CORREO_PROCURADOR,@TIPO_PODER);

	EXEC INSERTAR_PROCURADOR 1,'LUIS',218432,'LUIS@GMAIL.COM','JURIDICO'
	EXEC INSERTAR_PROCURADOR 2,'MARIA',213243,'MARIA@HOTMAIL.COM', 'FEDERAL'
	
	CREATE PROCEDURE INSERTAR_CLIENTE
	@IDENTIFICACION_CLIENTE BIGINT,
	@NOMBRE_CLIENTE VARCHAR (100),
	@CORREO_CLIENTE VARCHAR (100),
	@TELEFONO_CLIENTE BIGINT
	AS 
	INSERT INTO CLIENTE
	VALUES (@IDENTIFICACION_CLIENTE,@NOMBRE_CLIENTE,@CORREO_CLIENTE,@TELEFONO_CLIENTE);

	EXEC INSERTAR_CLIENTE 1,'JUAN','JUAN@YAHOO.COM',123342
	EXEC INSERTAR_CLIENTE 2,'GERMAN','GERMAN@GMAIL.COM',23324234
	EXEC INSERTAR_CLIENTE 3,'MERY','MERY@GMAIL.COM',123431

	CREATE PROCEDURE INSERTAR_GABINETE
	@NOMBRE_CARSO VARCHAR(100),
	@DESCRIPCION_CASO VARCHAR(200),
	@FECHA_INICIO DATETIME,
	@FECHA_FIN DATETIME,
	@ESTADO_CASO INT,
	@CLIENTE_CASO BIGINT,
	@PROCURADOR_CASO BIGINT
	AS
	INSERT INTO GABINETE
	VALUES (@NOMBRE_CARSO,@DESCRIPCION_CASO,@FECHA_INICIO,@FECHA_FIN,@ESTADO_CASO,@CLIENTE_CASO,@PROCURADOR_CASO);