GO 
USE KBAFFA
GO

-----CONEXIONES GABINETE-----

	ALTER TABLE GABINETE ADD CONSTRAINT ESTADO_CASO FOREIGN KEY (ESTADO_CASO) REFERENCES ESTADO (CODIGO_ESTADO);
	ALTER TABLE GABINETE ADD CLIENTE_CASO BIGINT FOREIGN KEY (CLIENTE_CASO) REFERENCES CLIENTE (IDENTIFICACION_CLIENTE);
	ALTER TABLE GABINETE ADD PROCURADOR_CASO BIGINT FOREIGN KEY (PROCURADOR_CASO) REFERENCES PROCURADOR (IDENTIFICACION_PROCURADOR);

	ALTER TABLE AGENDA ADD CONSTRAINT CASO FOREIGN KEY (CASO) REFERENCES GABINETE (CODIGO_CREDENCIAL);		
	ALTER TABLE AGENDA ADD PROCURADOR_AGENDA BIGINT FOREIGN KEY (PROCURADOR_AGENDA) REFERENCES PROCURADOR (IDENTIFICACION_PROCURADOR);
	ALTER TABLE AGENDA ADD CLIENTE_AGENDA BIGINT FOREIGN KEY (CLIENTE_AGENDA) REFERENCES CLIENTE (IDENTIFICACION_CLIENTE);

	SELECT *FROM AGENDA
	---DELETE GABINETE.ESTADO_CASO FROM GABINETE
	----ALTER TABLE GABINETE DROP COLUMN ESTADO_CASO
	----ALTER TABLE GABINETE ADD  ESTADO_CASO INT NOT NULL