GO 
USE KBAFFA
GO

-----CONEXIONES GABINETE-----

	ALTER TABLE GABINETE ADD CONSTRAINT ESTADO_CASO FOREIGN KEY (ESTADO_CASO) REFERENCES ESTADO (CODIGO_ESTADO);
	ALTER TABLE GABINETE ADD CLIENTE_CASO BIGINT FOREIGN KEY (CLIENTE_CASO) REFERENCES CLIENTE (IDENTIFICACION_CLIENTE);
	ALTER TABLE GABINETE ADD PROCURADOR_CASO BIGINT FOREIGN KEY (PROCURADOR_CASO) REFERENCES PROCURADOR (IDENTIFICACION_PROCURADOR);

	---DELETE GABINETE.ESTADO_CASO FROM GABINETE
	----ALTER TABLE GABINETE DROP COLUMN ESTADO_CASO
	----ALTER TABLE GABINETE ADD  ESTADO_CASO INT NOT NULL