GO
USE KBAFFA
GO

	-------ESPECIFICA
	CREATE PROCEDURE ESPECIFICA_ESTADO
	@CODIGO_ESTADO INT
	AS
	SELECT *FROM LLENAR_ESTADO
	WHERE Código = @CODIGO_ESTADO


	CREATE PROCEDURE ESPECIFICA_CLIENTE
	@IDENTIFICACION_CLIENTE BIGINT 
	AS
	SELECT *FROM LLENAR_CLIENTE
	WHERE Identificación = @IDENTIFICACION_CLIENTE

	CREATE PROCEDURE ESPECIFICA_PROCURADOR
	@IDENTIFICACION_PROCURADOR BIGINT 
	AS 
	SELECT *FROM LLENAR_PROCURADOR
	WHERE Identificación = @IDENTIFICACION_PROCURADOR
	
	CREATE PROCEDURE ESPECIFICA_GABINETE
	@CODIGO_CREDENCIAL BIGINT
	AS
	SELECT *FROM LLENAR_GABINETE
	WHERE [No Credencial] = @CODIGO_CREDENCIAL

	CREATE PROCEDURE ESPECIFICA_AGENDA
	@NUMERO_AGENDA BIGINT
	AS
	SELECT *FROM LLENAR_AGENDA
	WHERE Numero = @NUMERO_AGENDA
	-----NOMBRE
	CREATE PROCEDURE CONSULTA_ESTADO
	@NOMBRE_ESTADO VARCHAR(30)
	AS
	SELECT *FROM LLENAR_ESTADO
	WHERE Nombre LIKE @NOMBRE_ESTADO;

	CREATE PROCEDURE CONSULTA_CLIENTE
	@NOMBRE_CLIENTE VARCHAR (100)
	AS
	SELECT *FROM LLENAR_CLIENTE
	WHERE Cliente LIKE @NOMBRE_CLIENTE;

	CREATE PROCEDURE CONSULTA_PROCURADOR
	@NOMBRE_PROCURADOR VARCHAR (100)
	AS 
	SELECT *FROM LLENAR_PROCURADOR
	WHERE Nombre LIKE @NOMBRE_PROCURADOR

	CREATE PROCEDURE CONSULTA_GABINETE
	@NOMBRE_CASO VARCHAR (100)
	AS
	SELECT *FROM LLENAR_GABINETE


	--LLENADO
	CREATE VIEW LLENAR_CLIENTE
	AS
	SELECT C.IDENTIFICACION_CLIENTE AS [Identificación] , C.NOMBRE_CLIENTE AS [Cliente] , C.CORREO_CLIENTE AS [Correo Electrónico],
	C.TELEFONO_CLIENTE AS [Teléfono]
	FROM CLIENTE AS C

	CREATE VIEW LLENAR_ESTADO
	AS
	SELECT  E.CODIGO_ESTADO AS [Código] , E.NOMBRE_ESTADO AS [Nombre]
	FROM ESTADO AS [E]

	CREATE VIEW LLENAR_PROCURADOR
	AS
	SELECT P.IDENTIFICACION_PROCURADOR AS [Identificación], P.NOMBRE_PROCURADOR AS [Nombre] , P.TELEFONO_PROCURADOR AS [Teléfono], P.CORREO_PROCURADOR AS 
	[Correo Electrónico], P.TIPO_PODER AS [Poder]
	FROM PROCURADOR AS P

	CREATE VIEW LLENAR_GABINETE
	AS
	SELECT G.CODIGO_CREDENCIAL AS [No Credencial], G.NOMBRE_CASO AS [Caso],CLIENTE.NOMBRE_CLIENTE AS [Cliente], G.DESCRIPCION_CASO AS [Descripción],
	G.FECHA_INICIO AS [Inicio] , G.FECHA_FIN AS [Fin] ,ESTADO.NOMBRE_ESTADO  AS [Estado] , PROCURADOR.NOMBRE_PROCURADOR AS [Procurador]
	FROM GABINETE AS [G]
	INNER JOIN CLIENTE ON CLIENTE.IDENTIFICACION_CLIENTE = CLIENTE_CASO
	INNER JOIN ESTADO ON ESTADO.CODIGO_ESTADO = ESTADO_CASO
	INNER JOIN PROCURADOR ON PROCURADOR.IDENTIFICACION_PROCURADOR = PROCURADOR_CASO

	CREATE VIEW LLENAR_AGENDA
	AS
	SELECT AGENDA.NUMERO_AGENDA AS [Numero] , GABINETE.NOMBRE_CASO AS [Caso] , PROCURADOR.NOMBRE_PROCURADOR AS [Procurador], CLIENTE.NOMBRE_CLIENTE AS [Cliente]
	FROM AGENDA
	INNER JOIN GABINETE ON GABINETE.CODIGO_CREDENCIAL = AGENDA.CASO
	INNER JOIN PROCURADOR ON PROCURADOR.IDENTIFICACION_PROCURADOR = AGENDA.PROCURADOR_AGENDA
	INNER JOIN CLIENTE ON CLIENTE.IDENTIFICACION_CLIENTE = AGENDA.CLIENTE_AGENDA
