GO
USE KBAFFA
GO

	
	CREATE TRIGGER AGENDAR
	ON GABINETE FOR INSERT
	AS
	DECLARE @CASO AS BIGINT 
	DECLARE @PROCURADOR_AGENDA AS BIGINT
	DECLARE @CLIENTE_AGENDA AS BIGINT
	BEGIN
	 SET @CASO = (SELECT CODIGO_CREDENCIAL FROM inserted)
	 SET @PROCURADOR_AGENDA = (SELECT PROCURADOR_CASO FROM inserted)
	 SET @CLIENTE_AGENDA = (SELECT CLIENTE_CASO FROM inserted)
	 EXEC INSERTAR_AGENDA @CASO, @PROCURADOR_AGENDA,@CLIENTE_AGENDA
	 PRINT('Se agendaron los datos con éxito!')
	END

	ALTER TRIGGER ELIMINAR_AGENDA
	ON GABINETE FOR DELETE 
	AS
	DECLARE @CASO AS BIGINT 
	BEGIN
		SET @CASO = (SELECT CODIGO_CREDENCIAL FROM deleted)
		EXEC PROCELIMINAR_AGENDA @CASO
		PRINT ('Se han eliminado los datos y se ha desagendado')
	END

	CREATE TRIGGER ACTUALIZAR_AGENDA
	ON GABINETE FOR UPDATE
	AS
	DECLARE @CASO AS BIGINT
	DECLARE @PROCURADOR_AGENDA AS BIGINT 
	DECLARE @CLIENTE_AGENDA AS BIGINT
	DECLARE @NUMERO_AGENDA AS BIGINT
	BEGIN

		SET @CASO = (SELECT CODIGO_CREDENCIAL FROM inserted)
		SET @PROCURADOR_AGENDA = (SELECT PROCURADOR_CASO FROM inserted)
		SET @CLIENTE_AGENDA = (SELECT CLIENTE_CASO FROM inserted)
		SET @NUMERO_AGENDA = (SELECT NUMERO_AGENDA FROM AGENDA WHERE AGENDA.CASO = @CASO)

		EXEC MODIFICAR_AGENDA @NUMERO_AGENDA , @CASO , @PROCURADOR_AGENDA,@CLIENTE_AGENDA
		PRINT ('Datos y Agenda Actualizados')
	END

	SELECT *FROM LLENAR_AGENDA
	

	exec INSERTAR_GABINETE 'Colmenares', 'Asesinato','28/08/2001','29/09/2019',1,1,1
	SELECT *FROM LLENAR_GABINETE
	SELECT *FROM AGENDA
	SELECT *FROM GABINETE

	EXEC ELIMINAR_GABINETE 1 
	exec MODIFICAR_GABINETE 2 , 'Paulette' ,'Un misterioso caso','29/09/2019','23/09/2018',2 ,2,2
	SELECT *FROM LLENAR_AGENDA