GO
USE KBAFFA
GO

	CREATE PROCEDURE ELIMINAR_ESTADO
	@CODIGO_ESTADO INT
	AS
	DELETE ESTADO
	WHERE CODIGO_ESTADO = @CODIGO_ESTADO

	EXEC ELIMINAR_ESTADO 4

	CREATE PROCEDURE ELIMINAR_CLIENTE
	@IDENTIFICACION_CLIENTE BIGINT 
	AS
	DELETE CLIENTE
	WHERE IDENTIFICACION_CLIENTE = @IDENTIFICACION_CLIENTE

	CREATE PROCEDURE ELIMINAR_PROCURADOR
	@IDENTIFICACION_PROCURADOR BIGINT 
	AS
	DELETE PROCURADOR
	WHERE IDENTIFICACION_PROCURADOR = @IDENTIFICACION_PROCURADOR
	 
	CREATE PROCEDURE ELIMINAR_GABINETE
	@CODIGO_CREDENCIAL BIGINT
	AS
	DELETE GABINETE
	WHERE CODIGO_CREDENCIAL = @CODIGO_CREDENCIAL
