CREATE DATABASE KBAFFA

	CREATE TABLE ESTADO
	(
		CODIGO_ESTADO INT IDENTITY PRIMARY KEY NOT NULL,
		NOMBRE_ESTADO VARCHAR(30) NOT NULL
	) 
	CREATE TABLE CLIENTE
	(
		IDENTIFICACION_CLIENTE BIGINT PRIMARY KEY NOT NULL,
		NOMBRE_CLIENTE VARCHAR(100) NOT NULL,
		CORREO_CLIENTE VARCHAR(100) UNIQUE NOT NULL,
		TELEFONO_CLIENTE BIGINT NOT NULL
	)
	CREATE TABLE PROCURADOR
	(
		IDENTIFICACION_PROCURADOR BIGINT PRIMARY KEY NOT NULL,
		NOMBRE_PROCURADOR VARCHAR (100) NOT NULL,
		TELEFONO_PROCURADOR BIGINT NOT NULL,
		CORREO_PROCURADOR VARCHAR(100) UNIQUE NOT NULL,
		TIPO_PODER VARCHAR (100) NOT NULL
	)
	CREATE TABLE GABINETE
	(
		CODIGO_CREDENCIAL BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
		NOMBRE_CASO VARCHAR(100) NOT NULL,
		DESCRIPCION_CASO VARCHAR(200) NOT NULL,
		FECHA_INICIO DATETIME NOT NULL,
		FECHA_FIN DATETIME NOT NULL,
		ESTADO_CASO INT NOT NULL
	)
